(function(){
  const STATUS={idle:{label:'未执行',color:'#8c8c8c'},active:{label:'进行中',color:'#168df4'},done:{label:'已完成',color:'#52c41a'},half:{label:'时间过半',color:'#f6bd16'},ten:{label:'仅剩10秒',color:'#fa541c'},timeout:{label:'超时',color:'#f5222d'}};
  const rawSteps=[
    ['启动设备故障',180,['盯控、应急、非专业调度到岗到位']],
    ['相关人员建立沟通渠道',300,['通知工区工长值班人员','通知司机待命','通知车间值班干部、主任','通知段值班干部、值班领导、主要领导','建立应急群']],
    ['联系车站、登记停用',120,['故障登记','收集登记照片']],
    ['掌握人员动态与协调行车',180,['向电务调度汇报','向电务段汇报']],
    ['制定行车限制与调阅数据',180,['先通后复原则，拟定行车限制经审核批准后实施','调阅曲线监测数据、TDCS/CTC截图发应急群','通知调度室主任/技术科/安全科科长，打开大屏、视频','实时跟踪流程、群信息回复（专业对应）']],
    ['分析原因、制定方案与支援准备',300,[]],
    ['升级通知与梯队出动',300,['30分钟通知各主管领导、备班干部、专家组，提醒应急出动','15分钟无方向通知第二梯队出动，更新群消息','根据现场反馈指挥处置']],
    ['故障处理1小时卡控',600,['提醒故障处理已过1小时','卡控备班干部到位情况','根据现场反馈指挥处置']],
    ['复核设备状态',300,['提醒已过1.5小时，注意时间']],
    ['申请恢复使用',300,['提醒还有10分钟到2小时，注意时间']],
    ['销记并恢复行车',180,[]],
    ['整理应急资料',420,['生成速报']],
    ['复盘与闭环',300,[]]
  ];
  const initialElapsed=[180,360,45,100,175,0,0,0,0,0,0,0,0];
  const travelModes=['汽车','火车','动车','步行','轨道车'];
  const stepThreeChildren=[
    {name:'工区出行方式',type:'select',options:travelModes},
    {name:'车间出行方式',type:'select',options:travelModes},
    {name:'段出行方式',type:'select',options:travelModes},
    {name:'工区出发时间',type:'time'},
    {name:'车间出发时间',type:'time'},
    {name:'段出发时间',type:'time'},
    {name:'备品选择',type:'multi'},
    {name:'协调车站变通进路',type:'radio',options:['有变通进路','无变通进路']},
    {name:'协调行调添乘',type:'radio',options:['有添乘','无添乘']},
    {name:'向电务调度汇报',type:'check'}
  ];
  const customChildren={
    3:stepThreeChildren,
    5:[
      {name:'组织分析故障原因、启动预案、会商方案并发布',type:'plan'},
      {name:'盯控现场到位情况，投屏流程图，无头绪即联系专家组',type:'expert'},
      {name:'准备应急图纸；15分钟内研判影响，判断跨车间/工区支援',type:'check'}
    ],
    10:[
      {name:'联锁试验事前表格',type:'file'},
      {name:'联锁试验事后表格',type:'file'},
      {name:'销记照片',type:'file'},
      {name:'信息汇报',type:'check'},
      {name:'备品销号',type:'spareConsume'}
    ],
    12:[{name:'生成复盘报告',type:'report'}]
  };
  let state=null,timer=null,previewDrawer=null,previewClosing=false,previewScrollY=0;
  let resourceDrawer=null,resourceClosing=false,resourceTabKey='travel',resourceDeviceType='轨道电路',contactDraft=[],registerDraft='',spareDraft=[],libraryDraft='';
  const resourceTabs=[['travel','出行信息'],['contacts','联系人信息'],['docs','资料库'],['spares','备品库信息'],['plans','应急预案库信息'],['experts','专家库信息']];
  const emergencyDevices=[
    {id:'D001',type:'轨道电路',name:'ZPW-2000A发送器'},
    {id:'D002',type:'轨道电路',name:'轨道继电器'},
    {id:'D003',type:'轨道电路',name:'衰耗冗余控制器'},
    {id:'D004',type:'道岔',name:'S700K转辙机'},
    {id:'D005',type:'道岔',name:'道岔表示杆'},
    {id:'D006',type:'信号机',name:'LED信号灯盘'},
    {id:'D007',type:'信号机',name:'信号点灯单元'}
  ];
  const emergencyContacts=[
    {id:'P001',org:'示例二站工区',name:'王勇',phone:'138****2365',role:'工长'},
    {id:'P002',org:'示例二站工区',name:'李明',phone:'139****1278',role:'当前值班人员'},
    {id:'P003',org:'重庆信号车间',name:'陈杰',phone:'135****6882',role:'车间值班干部'},
    {id:'P004',org:'成都电务段',name:'赵强',phone:'136****9056',role:'段值班干部'},
    {id:'P005',org:'成都电务段',name:'刘洋',phone:'138****6650',role:'段值班领导'},
    {id:'P006',org:'成都电务段',name:'张明',phone:'137****2310',role:'段主要领导'},
    {id:'P007',org:'成都电务段',name:'周静',phone:'139****6721',role:'司机'},
    {id:'P008',org:'重庆信号车间',name:'孙磊',phone:'136****3188',role:'司机'}
  ];
  const registerTemplates=[
    {id:'R001',type:'轨道电路',name:'ZPW-2000A轨道电路',register:'因轨道电路红光带，申请登记停用相关区段设备。',cancel:'设备检查测试良好，故障处理完毕，申请销记恢复使用。',limit:'故障区段按站间闭塞办理，列车限速45km/h。'},
    {id:'R002',type:'轨道电路',name:'轨道继电器',register:'轨道继电器状态异常，登记停用并组织现场检查。',cancel:'继电器更换并复测合格，申请销记。',limit:'相关进路停止办理，按调度命令组织行车。'},
    {id:'R003',type:'道岔',name:'S700K转辙机',register:'道岔转换异常，申请登记停用该组道岔。',cancel:'道岔转换及表示试验正常，申请销记恢复。',limit:'道岔现场加锁，列车按引导方式通过。'},
    {id:'R004',type:'信号机',name:'LED信号机',register:'信号机显示异常，登记停用相关信号设备。',cancel:'显示状态复核正常，申请销记。',limit:'凭调度命令及引导信号组织行车。'}
  ];
  const resourceData={
    travel:[['段','应急指挥车','2026-09-25 08:20','2026-09-25 09:05','成都电务段'],['车间','抢修汽车','2026-09-25 08:28','2026-09-25 08:55','重庆信号车间'],['工区','工程作业车','2026-09-25 08:35','2026-09-25 08:50','示例二站']],
    selectedContacts:[['王勇','138****2365','工长'],['李明','139****1278','值班干部'],['赵强','136****9056','司机']],
    contacts:[['重庆信号车间','王勇','138****2365','工长'],['成都电务段','李明','139****1278','值班干部'],['示例二站工区','赵强','136****9056','司机'],['信号技术科','陈杰','135****6882','技术员']],
    docs:[['轨道电路故障应急处置手册.pdf','PDF'],['ZPW-2000A设备检修指导书.docx','Word'],['轨道电路故障案例汇编.pdf','PDF'],['现场检查记录模板.xlsx','Excel']],
    selectedSpares:[['轨道继电器','信号备品','2','示例二站备品间'],['发送器','轨道电路设备','1','重庆信号车间库']],
    spares:[['轨道继电器','信号备品','18','示例二站备品间'],['发送器','轨道电路设备','6','重庆信号车间库'],['接收器','轨道电路设备','8','成都电务段中心库'],['衰耗冗余控制器','轨道电路设备','4','示例三站备品间']],
    selectedPlans:[['示例二站','轨道电路故障应急预案','设备故障','一级预案','专项预案','2026-06-18']],
    plans:[['示例二站','轨道电路故障应急预案','设备故障','一级预案','专项预案','2026-06-18'],['示例三站','区间红光带处置预案','行车故障','二级预案','现场预案','2026-05-10'],['成都东站','轨道电路应急抢修方案','设备故障','一级预案','专项预案','2026-04-22']],
    selectedExperts:[['张明','137****2310']],
    experts:[['张明','成都电务段','信号高级工程师','137****2310'],['王建国','技术支持中心','轨道电路专家','136****9821'],['刘洋','重庆信号车间','高级技师','138****6650']]
  };
  function makeState(){return {mode:'default',selected:2,expanded:null,totalSeconds:23*60,boundDevices:[],boundContacts:[],selectedTemplate:'',steps:rawSteps.map((s,i)=>({id:i,name:s[0],limit:s[1],elapsed:initialElapsed[i],started:i>0&&i<5,children:(customChildren[i]||s[2].map(name=>({name,type:'check'}))).map((child,j)=>({...child,id:`${i}.${j+1}`,value:['multi','spareConsume'].includes(child.type)?[]:'',checked:false,locked:false}))}))}}
  function getStatus(step){if(step.children.length&&step.children.every(x=>x.checked))return 'done';if(!step.started)return 'idle';if(step.elapsed>step.limit)return 'timeout';const remain=step.limit-step.elapsed;if(remain<=10)return 'ten';if(step.elapsed>=step.limit/2)return 'half';return 'active'}
  function fmt(sec){const m=Math.floor(sec/60),s=sec%60;return `${m}:${String(s).padStart(2,'0')}`}
  function iconFor(i){return `assets/emergency-steps/step-${String(i+1).padStart(2,'0')}.png`}
  function jumpRail(){return `<nav class="ep-jump-rail" aria-label="流程快捷定位">${state.steps.map((step,i)=>{const key=getStatus(step),meta=STATUS[key];return `<button class="ep-jump ep-${key} ${i===state.selected?'active':''}" data-jump-step="${i}" title="步骤${i}：${meta.label}" aria-label="定位到步骤${i}，状态${meta.label}">${i}</button>`}).join('')}</nav>`}
  function childControl(child){if(child.type==='select')return `<select data-step-input="${child.id}"><option value="">请选择</option>${child.options.map(x=>`<option ${child.value===x?'selected':''}>${x}</option>`).join('')}</select>`;if(child.type==='time')return `<span class="ep-time-field"><input type="datetime-local" step="60" data-step-input="${child.id}" value="${child.value||''}" ${child.locked?'disabled':''} title="选择后无法更改"><small>选择后无法更改</small></span>`;if(child.type==='radio')return `<span class="ep-child-radios">${child.options.map(x=>`<label><input type="radio" name="step-${child.id}" data-step-input="${child.id}" value="${x}" ${child.value===x?'checked':''}>${x}</label>`).join('')}</span>`;if(child.type==='multi'||child.type==='spareConsume'){const values=Array.isArray(child.value)?child.value:[];return `<button type="button" class="ep-spare-trigger" data-open-spares="${child.id}" data-spare-mode="${child.type==='spareConsume'?'consume':'select'}" aria-haspopup="dialog"><span>${values.length?`已选 ${values.length} 项`:child.type==='spareConsume'?'请选择销号备品':'请选择备品'}</span><i aria-hidden="true">⌄</i></button>`}if(child.type==='plan'||child.type==='expert')return `<button type="button" class="ep-library-trigger" data-open-library="${child.type}" data-child-id="${child.id}">${child.value||`请选择${child.type==='plan'?'应急预案':'专家'}`}</button>`;if(child.type==='file')return `<label class="ep-upload-control"><input type="file" data-step-file="${child.id}" accept="image/*,.pdf,.doc,.docx,.xls,.xlsx"><span>${child.value||'上传文件/图片'}</span></label>`;if(child.type==='report')return `<button type="button" class="ep-report-trigger" data-generate-report="${child.id}">${child.checked?'重新生成':'生成报告'}</button>`;return `<label class="ep-form-check" aria-label="完成${child.name}"><input type="checkbox" data-child="${child.id}" ${child.checked?'checked':''}><i aria-hidden="true"></i></label>`}
  function childList(step){const form=step.children.some(child=>child.type!=='check');return `<div class="ep-children ${form?'ep-children-form':''}">${step.children.map(child=>`${form?'<div':'<label'} class="ep-child ${child.checked?'checked':''}"><span><b>${child.id}、</b>${child.name}</span>${childControl(child)}${form?'</div>':'</label>'}`).join('')}</div>`}
  function summary(step,i){const key=getStatus(step),meta=STATUS[key],pct=Math.min(100,Math.round(step.elapsed/step.limit*100)),bound=i===0&&state.boundDevices.length?`<button class="ep-bound-count" data-reselect-devices>已绑定 ${state.boundDevices.length} 台设备</button>`:i===1&&state.boundContacts.length?`<button class="ep-bound-count" data-reselect-contacts>已联系 ${state.boundContacts.length} 人</button>`:i===2&&state.selectedTemplate?`<button class="ep-bound-count" data-reselect-register title="${registerTemplates.find(x=>x.id===state.selectedTemplate)?.name||''}">已选模板</button>`:'';return `<div class="ep-step-head"><div class="ep-title"><img src="${iconFor(i)}" alt=""><b>${i}、${step.name}</b>${bound}</div><span class="ep-status ep-${key}">${meta.label}</span></div><div class="ep-metrics"><span>规定 ${fmt(step.limit)}</span><span>实际 ${fmt(step.elapsed)}</span></div><div class="ep-progress" aria-label="节点时间进度 ${pct}%"><i class="ep-${key}" style="width:${pct}%"></i></div>`}
  function previewSummary(step,i){const key=getStatus(step),meta=STATUS[key];return `<div class="ep-step-head"><div class="ep-title"><img src="${iconFor(i)}" alt=""><b>${i}、${step.name}</b></div><span class="ep-status ep-${key}">${meta.label}</span></div>`}
  function defaultCards(){return state.steps.map((step,i)=>{const expanded=state.expanded===i;return `<article class="ep-step ${i===state.selected?'active':''} ${expanded?'expanded':''}" data-step="${i}" tabindex="0">${summary(step,i)}<div class="ep-collapse">${childList(step)}</div></article>`}).join('')}
  function previewCards(){return state.steps.map((step,i)=>{const key=getStatus(step),meta=STATUS[key];return `<article class="ep-preview-row ${i===state.selected?'active':''}" data-step="${i}" tabindex="0" style="--ep-node-color:${meta.color}"><div class="ep-preview-main">${previewSummary(step,i)}</div>${childList(step)}</article>`}).join('')}
  function previewTreeNode(step,i){const key=getStatus(step),meta=STATUS[key];return `<article class="ep-mind-node ep-mind-${key}" data-preview-step="${i}" style="--ep-mind-color:${meta.color}"><header><img src="${iconFor(i)}" alt=""><b>${i}、${step.name}</b><span data-preview-status>${meta.label}</span></header><ul>${step.children.map(child=>`<li><i>${child.id}</i><em>${child.name}</em></li>`).join('')||'<li class="ep-mind-empty">暂无子项</li>'}</ul></article>`}
  function previewTreeMarkup(){const groups=[[0,1,2,3,4],[5,6,7,8],[9,10,11,12]];return `<div class="ep-mind-canvas"><section class="ep-mind-root"><strong>设备故障应急响应流程</strong><small>13 个流程节点 · ${state.steps.reduce((n,s)=>n+s.children.length,0)} 个处置子项</small></section><div class="ep-mind-groups">${groups.map((ids,index)=>`<section class="ep-mind-group ep-mind-group-${index+1}">${ids.map(i=>previewTreeNode(state.steps[i],i)).join('')}</section>`).join('')}</div></div>`}
  function updatePreviewDrawer(){if(!previewDrawer)return;const total=previewDrawer.querySelector('[data-preview-total]');if(total)total.textContent=`${Math.floor(state.totalSeconds/60)}分`;previewDrawer.querySelectorAll('[data-preview-step]').forEach(node=>{const step=state.steps[Number(node.dataset.previewStep)];if(!step)return;const key=getStatus(step),meta=STATUS[key];node.className=`ep-mind-node ep-mind-${key}`;node.style.setProperty('--ep-mind-color',meta.color);const badge=node.querySelector('[data-preview-status]');if(badge)badge.textContent=meta.label})}
  function lockPreviewPage(){previewScrollY=window.scrollY;document.body.style.top=`-${previewScrollY}px`;document.body.classList.add('ep-preview-open')}
  function unlockPreviewPage(){document.body.classList.remove('ep-preview-open');document.body.style.top='';window.scrollTo(0,previewScrollY)}
  function openPreviewDrawer(){if(previewDrawer||previewClosing)return;const shell=document.createElement('div');shell.className='ep-preview-shell';shell.innerHTML=`<div class="ep-preview-mask" data-preview-close></div><aside class="ep-preview-drawer" role="dialog" aria-modal="true" aria-labelledby="epPreviewTitle"><header><div><h2 id="epPreviewTitle">全流程预览</h2><p>成都站4设备类型“故障”应急响应流程</p></div><span class="ep-preview-time">累计时间：<b data-preview-total>${Math.floor(state.totalSeconds/60)}分</b></span><button data-preview-close aria-label="关闭全流程预览">×</button></header><div class="ep-preview-body"><div data-preview-canvas>${previewTreeMarkup()}</div></div></aside>`;document.body.appendChild(shell);previewDrawer=shell;lockPreviewPage();requestAnimationFrame(()=>shell.classList.add('open'))}
  function closePreviewDrawer(immediate=false){if(!previewDrawer||previewClosing)return;previewClosing=true;const shell=previewDrawer;shell.classList.remove('open');const done=()=>{shell.remove();if(previewDrawer===shell)previewDrawer=null;previewClosing=false;unlockPreviewPage()};if(immediate)done();else setTimeout(done,260)}
  function flowMarkup(){return `<aside class="ep-flow ${state.mode==='preview'?'ep-preview':''}" aria-label="应急响应步骤">${state.mode==='preview'?previewCards():defaultCards()}</aside>`}
  function toolbar(){return `<header class="ep-toolbar"><h2>设备故障应急响应流程</h2><span class="ep-countdown"><i class="ep-clock">◷</i><span>累计时间：<b data-total-time>${Math.floor(state.totalSeconds/60)}分</b></span></span><div class="ep-view-switch" role="group" aria-label="阅览模式"><button data-view-mode="preview" aria-haspopup="dialog">全流程预览</button><button data-view-mode="default" class="active">默认视图</button></div><div class="ep-toolbar-actions"><label>应急故障 <select id="epFault"><option>成都站4设备类型“故障”启动时间（YYYYMMDDHHMMSS）</option><option>轨道电路故障</option><option>道岔设备故障</option></select></label><button class="ep-material">应急资料调用</button></div></header>`}
  function view(){clearInterval(timer);state=makeState();const station=sessionStorage.getItem('emergency-station')||'示例三站';setTimeout(startTimer,0);return `<div class="emergency-process-page"><nav class="ep-breadcrumb"><button class="ep-back">返回</button><span>/</span><b>故障一点通详情</b></nav><section class="ep-workspace">${toolbar()}<div class="ep-content"><div data-jump-host>${jumpRail()}</div><div data-flow-host>${flowMarkup()}</div><section class="ep-map-card"><img src="assets/panorama-screen/map.jpeg" alt="成渝中线应急处置线路图"><div class="ep-map-caption"><b>${station}</b><span>当前应急处置车站</span></div></section></div></section></div>`}
  function renderFlow({keepScroll=true}={}){const host=document.querySelector('[data-flow-host]'),jump=document.querySelector('[data-jump-host]');if(!host||!jump)return;const old=host.querySelector('.ep-flow'),top=old?.scrollTop||0;host.innerHTML=flowMarkup();jump.innerHTML=jumpRail();if(keepScroll)host.querySelector('.ep-flow').scrollTop=top;document.querySelectorAll('[data-view-mode]').forEach(b=>b.classList.toggle('active',b.dataset.viewMode===state.mode))}
  function scrollStep(i){const card=document.querySelector(`[data-flow-host] [data-step="${i}"]`),flow=card?.closest('.ep-flow');if(!card||!flow)return;const top=card.offsetTop-(flow.clientHeight-card.offsetHeight)/2;flow.scrollTo({top:Math.max(0,top),behavior:'smooth'})}
  function selectStep(i,{toggle=false}={}){state.selected=i;state.steps[i].started=true;if(state.mode==='default')state.expanded=toggle&&state.expanded===i?null:i;renderFlow();requestAnimationFrame(()=>scrollStep(i))}
  function completeStep(i){const step=state.steps[i];if(!step.children.every(x=>x.checked))return;step.elapsed=Math.min(step.elapsed,step.limit);if(i<state.steps.length-1){const next=state.steps[i+1];state.selected=i+1;state.expanded=i+1;next.started=true;next.elapsed=0;renderFlow();requestAnimationFrame(()=>scrollStep(i+1))}else{state.expanded=null;renderFlow();showToast('应急流程已全部完成') }}
  function toggleChild(input){const [i]=input.dataset.child.split('.').map(Number),step=state.steps[i],child=step.children.find(x=>x.id===input.dataset.child);child.checked=input.checked;if(!input.checked){step.started=true;step.elapsed=0}renderFlow();if(input.checked)completeStep(i)}
  function updateStepControl(input){const id=input.dataset.stepInput,[i]=id.split('.').map(Number),step=state.steps[i],child=step.children.find(x=>x.id===id);child.value=input.type==='checkbox'?input.checked:input.value;child.checked=input.type==='checkbox'?input.checked:!!input.value;if(child.type==='time'&&input.value){child.locked=true;showToast('出发时间已确定，选择后无法更改')}step.started=true;renderFlow();if(child.checked)completeStep(i)}
  function showToast(msg){const toast=document.querySelector('#toast');if(!toast)return;toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1700)}
  function deviceRows(type='',name='',selected=[]){const rows=emergencyDevices.filter(x=>(!type||x.type===type)&&(!name||x.name.includes(name)));return rows.length?rows.map(x=>`<tr><td><input type="checkbox" data-device-id="${x.id}" ${selected.includes(x.id)?'checked':''}></td><td>${x.type}</td><td>${x.name}</td></tr>`).join(''):`<tr><td colspan="3" class="ep-device-empty">暂无符合条件的设备</td></tr>`}
  function openDevicePicker(){if(document.querySelector('.ep-device-shell'))return;const selected=[...state.boundDevices],shell=document.createElement('div');shell.className='ep-device-shell';shell.innerHTML=`<div class="ep-device-mask" data-device-close></div><section class="ep-device-dialog" role="dialog" aria-modal="true" aria-labelledby="epDeviceTitle"><header><h2 id="epDeviceTitle">选择应急设备</h2><button data-device-close aria-label="关闭">×</button></header><div class="ep-device-filters"><label>设备类型<select data-device-type><option value="">全部</option><option>轨道电路</option><option>道岔</option><option>信号机</option></select></label><label>设备名称<input data-device-name placeholder="请输入设备名称"></label><button data-device-query>查询</button><button data-device-reset>重置</button></div><div class="ep-device-table-wrap"><table><thead><tr><th class="ep-device-check"><input type="checkbox" data-device-all aria-label="全选"></th><th>设备类型</th><th>设备名称</th></tr></thead><tbody data-device-rows>${deviceRows('', '', selected)}</tbody></table></div><footer><button class="ep-device-skip" data-device-skip>跳过</button><button class="ep-device-confirm" data-device-confirm>确认</button></footer></section>`;document.body.appendChild(shell);requestAnimationFrame(()=>shell.classList.add('open'))}
  function closeDevicePicker(){const shell=document.querySelector('.ep-device-shell');if(!shell)return;shell.classList.remove('open');setTimeout(()=>shell.remove(),200)}
  function filterDevices(reset=false){const shell=document.querySelector('.ep-device-shell');if(!shell)return;const type=shell.querySelector('[data-device-type]'),name=shell.querySelector('[data-device-name]');if(reset){type.value='';name.value=''}const selected=[...shell.querySelectorAll('[data-device-id]:checked')].map(x=>x.dataset.deviceId);shell.querySelector('[data-device-rows]').innerHTML=deviceRows(type.value,name.value.trim(),selected);shell.querySelector('[data-device-all]').checked=false}
  function confirmDevices(){const shell=document.querySelector('.ep-device-shell');if(!shell)return;state.boundDevices=[...shell.querySelectorAll('[data-device-id]:checked')].map(x=>x.dataset.deviceId);if(state.boundDevices.length){state.selected=0;state.expanded=0;state.steps[0].started=true}closeDevicePicker();renderFlow();if(state.boundDevices.length)requestAnimationFrame(()=>scrollStep(0));showToast(state.boundDevices.length?`已绑定 ${state.boundDevices.length} 台设备`:'未选择设备')}
  function spareRows(type='',selected=[]){const rows=resourceData.spares.filter(x=>!type||x[1]===type);return rows.length?rows.map(x=>`<tr><td><input type="checkbox" data-spare-name="${x[0]}" ${selected.includes(x[0])?'checked':''} aria-label="选择${x[0]}"></td><td>${x[0]}</td><td>${x[1]}</td><td>${x[2]}</td><td>${x[3]}</td></tr>`).join(''):`<tr><td colspan="5" class="ep-device-empty">暂无符合条件的备品</td></tr>`}
  function openSparePicker(childId='3.7',mode='select'){if(document.querySelector('.ep-spare-shell'))return;const [stepIndex]=childId.split('.').map(Number),child=state.steps[stepIndex]?.children.find(x=>x.id===childId);if(!child)return;const previous=state.steps[3]?.children.find(x=>x.id==='3.7')?.value||[];spareDraft=[...(Array.isArray(child.value)&&child.value.length?child.value:mode==='consume'?previous:[])];const types=[...new Set(resourceData.spares.map(x=>x[1]))],shell=document.createElement('div');shell.className='ep-device-shell ep-spare-shell';shell.dataset.childId=childId;shell.dataset.spareMode=mode;shell.innerHTML=`<div class="ep-device-mask" data-spare-close></div><section class="ep-device-dialog ep-spare-dialog" role="dialog" aria-modal="true" aria-labelledby="epSpareTitle"><header><h2 id="epSpareTitle">${mode==='consume'?'选择销号备品':'选择备品'}</h2><button data-spare-close aria-label="关闭">×</button></header><div class="ep-device-filters"><label>设备类型<select data-spare-type><option value="">全部</option>${types.map(x=>`<option>${x}</option>`).join('')}</select></label><button data-spare-query>查询</button><button data-spare-reset>重置</button></div><div class="ep-device-table-wrap ep-spare-table"><table><thead><tr><th class="ep-device-check"><input type="checkbox" data-spare-all aria-label="全选"></th><th>名称</th><th>类型</th><th>数量</th><th>存储地点</th></tr></thead><tbody data-spare-rows>${spareRows('',spareDraft)}</tbody></table></div><footer><button data-spare-close>取消</button><button class="ep-device-confirm" data-spare-confirm>确认</button></footer></section>`;document.body.appendChild(shell);requestAnimationFrame(()=>shell.classList.add('open'))}
  function closeSparePicker(){const shell=document.querySelector('.ep-spare-shell');if(!shell)return;shell.classList.remove('open');setTimeout(()=>shell.remove(),200)}
  function filterSpares(reset=false){const shell=document.querySelector('.ep-spare-shell');if(!shell)return;const type=shell.querySelector('[data-spare-type]');if(reset)type.value='';shell.querySelector('[data-spare-rows]').innerHTML=spareRows(type.value,spareDraft);shell.querySelector('[data-spare-all]').checked=false}
  function confirmSpares(){const shell=document.querySelector('.ep-spare-shell');if(!shell)return;const id=shell.dataset.childId,[i]=id.split('.').map(Number),step=state.steps[i],child=step.children.find(x=>x.id===id),consume=shell.dataset.spareMode==='consume';child.value=[...spareDraft];child.checked=spareDraft.length>0;step.started=true;if(consume&&child.checked)resourceData.spares.forEach(row=>{if(spareDraft.includes(row[0]))row[2]=String(Math.max(0,Number(row[2])-1))});closeSparePicker();renderFlow();if(child.checked)completeStep(i);showToast(spareDraft.length?consume?`已销号 ${spareDraft.length} 项备品`:`已选择 ${spareDraft.length} 项备品`:'未选择备品')}
  function libraryRows(kind,selected=''){const rows=kind==='plan'?resourceData.plans:resourceData.experts,headers=kind==='plan'?['车站','名称','类型','分类','类别','时间']:['姓名','部门','职位','联系方式'];return {headers,html:rows.map((row,i)=>`<tr><td class="ep-register-select"><input type="radio" name="libraryItem" data-library-select="${i}" ${selected===String(i)?'checked':''}></td>${row.map(x=>`<td title="${x}">${x}</td>`).join('')}</tr>`).join('')}}
  function openLibraryPicker(kind,childId){if(document.querySelector('.ep-library-shell'))return;const [i]=childId.split('.').map(Number),child=state.steps[i]?.children.find(x=>x.id===childId);if(!child)return;libraryDraft='';const table=libraryRows(kind),shell=document.createElement('div');shell.className='ep-device-shell ep-library-shell';shell.dataset.kind=kind;shell.dataset.childId=childId;shell.innerHTML=`<div class="ep-device-mask" data-library-close></div><section class="ep-device-dialog ep-library-dialog" role="dialog" aria-modal="true"><header><h2>选择${kind==='plan'?'应急预案':'专家'}</h2><button data-library-close aria-label="关闭">×</button></header><div class="ep-device-filters"><label>设备类型<select><option>轨道电路</option><option>道岔</option><option>信号机</option></select></label></div><div class="ep-device-table-wrap"><table><thead><tr><th>选择</th>${table.headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${table.html}</tbody></table></div><footer><button data-library-close>取消</button><button class="ep-device-confirm" data-library-confirm>确认</button></footer></section>`;document.body.appendChild(shell);requestAnimationFrame(()=>shell.classList.add('open'))}
  function closeLibraryPicker(){const shell=document.querySelector('.ep-library-shell');if(!shell)return;shell.classList.remove('open');setTimeout(()=>shell.remove(),200)}
  function confirmLibrary(){const shell=document.querySelector('.ep-library-shell');if(!shell||libraryDraft===''){showToast('请先选择一项');return}const kind=shell.dataset.kind,id=shell.dataset.childId,[i]=id.split('.').map(Number),child=state.steps[i].children.find(x=>x.id===id),row=(kind==='plan'?resourceData.plans:resourceData.experts)[Number(libraryDraft)];child.value=kind==='plan'?row[1]:row[0];child.checked=true;state.steps[i].started=true;if(kind==='plan')resourceData.selectedPlans=[row];else resourceData.selectedExperts=[[row[0],row[3]]];closeLibraryPicker();renderFlow();completeStep(i);showToast(`已选择${kind==='plan'?'应急预案':'专家'}`)}
  function generateReport(childId){const [i]=childId.split('.').map(Number),child=state.steps[i].children.find(x=>x.id===childId);child.checked=true;child.value='应急处置复盘报告';const shell=document.createElement('div');shell.className='ep-device-shell ep-report-shell';shell.innerHTML=`<div class="ep-device-mask" data-report-close></div><section class="ep-device-dialog ep-report-dialog" role="dialog" aria-modal="true"><header><h2>应急处置复盘报告</h2><button data-report-close>×</button></header><div class="ep-report-preview"><h3>成渝中线设备故障应急处置复盘报告</h3><p>系统已根据指定模板汇总流程节点、处置时间、联系人、设备及资料调用记录。</p><dl><dt>流程节点</dt><dd>13 个</dd><dt>已完成节点</dt><dd>${state.steps.filter(x=>getStatus(x)==='done').length} 个</dd><dt>累计时间</dt><dd>${Math.floor(state.totalSeconds/60)} 分钟</dd></dl></div><footer><button data-report-download>下载报告</button><button class="ep-device-confirm" data-report-close>完成</button></footer></section>`;document.body.appendChild(shell);requestAnimationFrame(()=>shell.classList.add('open'));renderFlow();completeStep(i)}
  function closeReport(){const shell=document.querySelector('.ep-report-shell');if(!shell)return;shell.classList.remove('open');setTimeout(()=>shell.remove(),200)}
  function contactRows(org='',name='',selected=[]){const rows=emergencyContacts.filter(x=>(!org||x.org===org)&&(!name||x.name.includes(name)));return rows.length?rows.map(x=>`<tr><td><input type="checkbox" data-contact-id="${x.id}" ${selected.includes(x.id)?'checked':''}></td><td>${x.org}</td><td>${x.name}</td><td>${x.phone}</td><td>${x.role}</td></tr>`).join(''):`<tr><td colspan="5" class="ep-device-empty">暂无符合条件的人员</td></tr>`}
  function selectedContactTable(ids){const rows=ids.map(id=>emergencyContacts.find(x=>x.id===id)).filter(Boolean);return rows.length?`<table><thead><tr><th>组织机构</th><th>姓名</th><th>联系方式</th><th>职务</th><th>操作</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.org}</td><td>${x.name}</td><td>${x.phone}</td><td>${x.role}</td><td><button data-contact-remove="${x.id}">删除</button></td></tr>`).join('')}</tbody></table>`:`<div class="ep-contact-empty">暂未选择联系人</div>`}
  function syncContactSelected(){const shell=document.querySelector('.ep-contact-shell');if(!shell)return;shell.querySelector('[data-contact-selected]').innerHTML=selectedContactTable(contactDraft);shell.querySelectorAll('[data-contact-id]').forEach(x=>x.checked=contactDraft.includes(x.dataset.contactId))}
  function openContactPicker(){if(document.querySelector('.ep-contact-shell'))return;contactDraft=[...state.boundContacts];const orgs=[...new Set(emergencyContacts.map(x=>x.org))],shell=document.createElement('div');shell.className='ep-device-shell ep-contact-shell';shell.innerHTML=`<div class="ep-device-mask" data-contact-close></div><section class="ep-device-dialog ep-contact-dialog" role="dialog" aria-modal="true" aria-labelledby="epContactTitle"><header><h2 id="epContactTitle">选择应急联系人</h2><button data-contact-close aria-label="关闭">×</button></header><div class="ep-contact-selected"><h3>已联系人</h3><div class="ep-contact-selected-table" data-contact-selected>${selectedContactTable(contactDraft)}</div></div><div class="ep-device-filters"><label>组织机构<select data-contact-org><option value="">全部</option>${orgs.map(x=>`<option>${x}</option>`).join('')}</select></label><label>姓名<input data-contact-name placeholder="请输入姓名"></label><button data-contact-query>查询</button><button data-contact-reset>重置</button></div><div class="ep-device-table-wrap ep-contact-table"><table><thead><tr><th class="ep-device-check"><input type="checkbox" data-contact-all aria-label="全选"></th><th>组织机构</th><th>姓名</th><th>联系方式</th><th>职务</th></tr></thead><tbody data-contact-rows>${contactRows('', '', contactDraft)}</tbody></table></div><footer><button class="ep-device-skip" data-contact-skip>跳过</button><button class="ep-device-confirm" data-contact-confirm>确认</button></footer></section>`;document.body.appendChild(shell);requestAnimationFrame(()=>shell.classList.add('open'))}
  function closeContactPicker(){const shell=document.querySelector('.ep-contact-shell');if(!shell)return;shell.classList.remove('open');setTimeout(()=>shell.remove(),200)}
  function filterContacts(reset=false){const shell=document.querySelector('.ep-contact-shell');if(!shell)return;const org=shell.querySelector('[data-contact-org]'),name=shell.querySelector('[data-contact-name]');if(reset){org.value='';name.value=''}shell.querySelector('[data-contact-rows]').innerHTML=contactRows(org.value,name.value.trim(),contactDraft);shell.querySelector('[data-contact-all]').checked=false}
  function confirmContacts(){const shell=document.querySelector('.ep-contact-shell');if(!shell)return;state.boundContacts=[...contactDraft];if(state.boundContacts.length){state.selected=1;state.expanded=1;state.steps[1].started=true}closeContactPicker();renderFlow();if(state.boundContacts.length)requestAnimationFrame(()=>scrollStep(1));showToast(state.boundContacts.length?`已添加 ${state.boundContacts.length} 位联系人`:'未选择联系人')}
  function registerRows(type='',name=''){const rows=registerTemplates.filter(x=>(!type||x.type===type)&&(!name||x.name.includes(name)));return rows.length?rows.map(x=>`<tr class="${registerDraft===x.id?'selected':''}"><td class="ep-register-select"><input type="radio" name="registerTemplate" data-register-select="${x.id}" ${registerDraft===x.id?'checked':''} aria-label="选择${x.name}"></td><td>${x.name}</td><td title="${x.register}">${x.register}</td><td title="${x.cancel}">${x.cancel}</td><td title="${x.limit}">${x.limit}</td><td><button data-register-view="${x.id}">查看</button></td></tr>`).join(''):`<tr><td colspan="6" class="ep-device-empty">暂无符合条件的模板</td></tr>`}
  function openRegisterTemplates(){if(document.querySelector('.ep-register-shell'))return;registerDraft=state.selectedTemplate;const shell=document.createElement('div');shell.className='ep-device-shell ep-register-shell';shell.innerHTML=`<div class="ep-device-mask" data-register-close></div><section class="ep-device-dialog ep-register-dialog" role="dialog" aria-modal="true" aria-labelledby="epRegisterTitle"><header><h2 id="epRegisterTitle">登销记模板列表</h2><button data-register-close aria-label="关闭">×</button></header><div class="ep-device-filters"><label>设备名称<input data-register-name placeholder="请输入设备名称"></label><label>设备类型<select data-register-type><option value="">全部</option><option>轨道电路</option><option>道岔</option><option>信号机</option></select></label><button data-register-query>查询</button><button data-register-reset>重置</button></div><div class="ep-device-table-wrap ep-register-table"><table><thead><tr><th class="ep-register-select">选择</th><th>设备名称</th><th>登记内容</th><th>销记内容</th><th>行车限制条件登记内容</th><th>操作</th></tr></thead><tbody data-register-rows>${registerRows()}</tbody></table></div><div class="ep-register-detail" data-register-detail hidden></div><footer><button data-register-close>取消</button><button class="ep-device-confirm" data-register-confirm>确认</button></footer></section>`;document.body.appendChild(shell);requestAnimationFrame(()=>shell.classList.add('open'))}
  function closeRegisterTemplates(){const shell=document.querySelector('.ep-register-shell');if(!shell)return;shell.classList.remove('open');setTimeout(()=>shell.remove(),200)}
  function filterRegisterTemplates(reset=false){const shell=document.querySelector('.ep-register-shell');if(!shell)return;const type=shell.querySelector('[data-register-type]'),name=shell.querySelector('[data-register-name]');if(reset){type.value='';name.value=''}shell.querySelector('[data-register-rows]').innerHTML=registerRows(type.value,name.value.trim());shell.querySelector('[data-register-detail]').hidden=true}
  function showRegisterDetail(id){const item=registerTemplates.find(x=>x.id===id),detail=document.querySelector('[data-register-detail]');if(!item||!detail)return;detail.hidden=false;detail.innerHTML=`<h3>${item.name}</h3><dl><dt>登记内容</dt><dd>${item.register}</dd><dt>销记内容</dt><dd>${item.cancel}</dd><dt>行车限制条件登记内容</dt><dd>${item.limit}</dd></dl>`}
  function confirmRegisterTemplate(){if(!registerDraft){showToast('请先选择登销记模板');return}state.selectedTemplate=registerDraft;state.selected=2;state.expanded=2;state.steps[2].started=true;closeRegisterTemplates();renderFlow();requestAnimationFrame(()=>scrollStep(2));showToast('登销记模板已确认')}
  function resourceTable(headers,rows,{actions=false}={}){return `<div class="ep-resource-table-wrap"><table class="ep-resource-table"><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}${actions?'<th>操作</th>':''}</tr></thead><tbody>${rows.map((row,i)=>`<tr>${row.map(x=>`<td title="${x}">${x}</td>`).join('')}${actions?`<td><button data-resource-action="preview">预览</button><button data-resource-action="download">下载</button></td>`:''}</tr>`).join('')}</tbody></table></div>`}
  function selectedBlock(title,content){return `<section class="ep-resource-section ep-resource-selected"><h3>${title}</h3>${content}</section>`}
  function resourceFilter(){return `<div class="ep-resource-filter"><label><span>设备类型</span><select data-resource-device aria-label="设备类型"><option ${resourceDeviceType==='轨道电路'?'selected':''}>轨道电路</option><option ${resourceDeviceType==='道岔'?'selected':''}>道岔</option><option ${resourceDeviceType==='信号机'?'selected':''}>信号机</option></select></label></div>`}
  function resourcePanel(key){
    if(key==='travel')return `<section class="ep-resource-section"><h3>三级出行信息</h3>${resourceTable(['级别','出行方式','出发时间','预计到达时间','地点'],resourceData.travel)}</section>`;
    if(key==='contacts'){const selected=state.boundContacts.map(id=>emergencyContacts.find(x=>x.id===id)).filter(Boolean).map(x=>[x.name,x.phone,x.role]);return `${selectedBlock('步骤一已选联系人',resourceTable(['姓名','联系方式','职务'],selected))}<section class="ep-resource-section"><h3>人员列表</h3>${resourceTable(['部门','姓名','联系方式','职务'],resourceData.contacts)}</section>`}
    if(key==='docs')return `${resourceFilter()}<section class="ep-resource-section"><h3>资料库 <small>已按设备类型：${resourceDeviceType}筛选</small></h3>${resourceTable(['文件名','类型'],resourceData.docs,{actions:true})}</section>`;
    if(key==='spares')return `${resourceFilter()}${selectedBlock('步骤三已选备品',resourceTable(['名称','类型','数量','存储地点'],resourceData.selectedSpares))}<section class="ep-resource-section"><h3>备品库 <small>已按设备类型：${resourceDeviceType}筛选</small></h3>${resourceTable(['名称','类型','数量','存储地点'],resourceData.spares)}</section>`;
    if(key==='plans')return `${resourceFilter()}${selectedBlock('步骤五已选预案',resourceTable(['车站','名称','类型','分类','类别','时间'],resourceData.selectedPlans,{actions:true}))}<section class="ep-resource-section"><h3>应急预案库 <small>已按设备类型：${resourceDeviceType}筛选</small></h3>${resourceTable(['车站','名称','类型','分类','类别','时间'],resourceData.plans,{actions:true})}</section>`;
    if(key==='experts')return `${resourceFilter()}${selectedBlock('步骤五已选专家',resourceTable(['姓名','联系方式'],resourceData.selectedExperts))}<section class="ep-resource-section"><h3>专家库 <small>已按设备类型：${resourceDeviceType}筛选</small></h3>${resourceTable(['姓名','部门','职位','联系方式'],resourceData.experts)}</section>`;
    return `<section class="ep-resource-section"><h3>三级出行信息</h3>${resourceTable(['级别','出行方式','出发时间','预计到达时间','地点'],resourceData.travel)}</section>`;
  }
  function setResourceTab(key){if(!resourceDrawer)return;resourceTabKey=key;resourceDrawer.querySelectorAll('[data-resource-tab]').forEach(x=>x.classList.toggle('active',x.dataset.resourceTab===key));resourceDrawer.querySelector('[data-resource-body]').innerHTML=resourcePanel(key)}
  function openResourceDrawer(){if(resourceDrawer){setResourceTab('travel');return}resourceClosing=false;resourceTabKey='travel';resourceDeviceType='轨道电路';const shell=document.createElement('div');shell.className='ep-resource-shell';shell.innerHTML=`<div class="ep-resource-mask" data-resource-close></div><aside class="ep-resource-drawer" role="dialog" aria-modal="true" aria-labelledby="epResourceTitle"><header><h2 id="epResourceTitle">应急资料调用</h2><button data-resource-close aria-label="关闭">×</button></header><nav class="ep-resource-tabs">${resourceTabs.map(([key,label],i)=>`<button data-resource-tab="${key}" class="${i===0?'active':''}">${label}</button>`).join('')}</nav><div class="ep-resource-body" data-resource-body>${resourcePanel('travel')}</div></aside>`;document.body.appendChild(shell);resourceDrawer=shell;document.body.classList.add('ep-resource-open');requestAnimationFrame(()=>shell.classList.add('open'))}
  function closeResourceDrawer(immediate=false){if(!resourceDrawer||resourceClosing)return;resourceClosing=true;const shell=resourceDrawer;shell.classList.remove('open');document.body.classList.remove('ep-resource-open');const done=()=>{shell.remove();if(resourceDrawer===shell)resourceDrawer=null;resourceClosing=false};if(immediate)done();else setTimeout(done,240)}
  function updateLiveStep(i){const step=state.steps[i],key=getStatus(step),meta=STATUS[key],pct=Math.min(100,Math.round(step.elapsed/step.limit*100)),card=document.querySelector(`[data-flow-host] [data-step="${i}"]`),jump=document.querySelector(`[data-jump-step="${i}"]`);if(card){card.style.setProperty('--ep-node-color',meta.color);const badge=card.querySelector('.ep-status');if(badge){badge.className=`ep-status ep-${key}`;badge.textContent=meta.label}const actual=card.querySelector('.ep-metrics span:nth-child(2)');if(actual)actual.textContent=`实际 ${fmt(step.elapsed)}`;const bar=card.querySelector('.ep-progress i');if(bar){bar.className=`ep-${key}`;bar.style.width=`${pct}%`;bar.parentElement.setAttribute('aria-label',`节点时间进度 ${pct}%`)}}if(jump){jump.className=`ep-jump ep-${key} ${i===state.selected?'active':''}`;jump.title=`步骤${i}：${meta.label}`;jump.setAttribute('aria-label',`定位到步骤${i}，状态${meta.label}`)}}
  function startTimer(){clearInterval(timer);timer=setInterval(()=>{if(!document.querySelector('.emergency-process-page')){clearInterval(timer);timer=null;closePreviewDrawer(true);return}state.totalSeconds++;const step=state.steps[state.selected];if(step&&getStatus(step)!=='done'&&step.started)step.elapsed++;updateLiveStep(state.selected);const total=document.querySelector('[data-total-time]');if(total)total.textContent=`${Math.floor(state.totalSeconds/60)}分`;updatePreviewDrawer()},1000)}
  window.PageViews.emergencyProcess=view;
  document.addEventListener('click',e=>{
    if(e.target.closest('.ep-back')){location.hash='#/panorama/emergency';return}
    if(e.target.closest('.ep-material')){openResourceDrawer();return}
    if(e.target.closest('[data-device-close]')){closeDevicePicker();return}
    if(e.target.closest('[data-device-query]')){filterDevices();return}
    if(e.target.closest('[data-device-reset]')){filterDevices(true);return}
    if(e.target.closest('[data-device-confirm]')){confirmDevices();return}
    if(e.target.closest('[data-device-skip]')){closeDevicePicker();showToast('已跳过设备绑定');return}
    if(e.target.closest('[data-reselect-devices]')){openDevicePicker();return}
    const openSpare=e.target.closest('[data-open-spares]');if(openSpare){openSparePicker(openSpare.dataset.openSpares,openSpare.dataset.spareMode||'select');return}
    if(e.target.closest('[data-spare-close]')){closeSparePicker();return}
    if(e.target.closest('[data-spare-query]')){filterSpares();return}
    if(e.target.closest('[data-spare-reset]')){filterSpares(true);return}
    if(e.target.closest('[data-spare-confirm]')){confirmSpares();return}
    const openLibrary=e.target.closest('[data-open-library]');if(openLibrary){openLibraryPicker(openLibrary.dataset.openLibrary,openLibrary.dataset.childId);return}
    if(e.target.closest('[data-library-close]')){closeLibraryPicker();return}
    if(e.target.closest('[data-library-confirm]')){confirmLibrary();return}
    const report=e.target.closest('[data-generate-report]');if(report){generateReport(report.dataset.generateReport);return}
    if(e.target.closest('[data-report-close]')){closeReport();return}
    if(e.target.closest('[data-report-download]')){showToast('复盘报告已生成并开始模拟下载');return}
    if(e.target.closest('[data-reselect-contacts]')){openContactPicker();return}
    if(e.target.closest('[data-reselect-register]')){openRegisterTemplates();return}
    if(e.target.closest('[data-contact-close]')){closeContactPicker();return}
    if(e.target.closest('[data-contact-query]')){filterContacts();return}
    if(e.target.closest('[data-contact-reset]')){filterContacts(true);return}
    if(e.target.closest('[data-contact-confirm]')){confirmContacts();return}
    if(e.target.closest('[data-contact-skip]')){closeContactPicker();showToast('已跳过联系人选择');return}
    const removeContact=e.target.closest('[data-contact-remove]');if(removeContact){contactDraft=contactDraft.filter(id=>id!==removeContact.dataset.contactRemove);syncContactSelected();return}
    if(e.target.closest('[data-register-close]')){closeRegisterTemplates();return}
    if(e.target.closest('[data-register-query]')){filterRegisterTemplates();return}
    if(e.target.closest('[data-register-reset]')){filterRegisterTemplates(true);return}
    if(e.target.closest('[data-register-confirm]')){confirmRegisterTemplate();return}
    const registerView=e.target.closest('[data-register-view]');if(registerView){showRegisterDetail(registerView.dataset.registerView);return}
    if(e.target.closest('[data-resource-close]')){closeResourceDrawer();return}
    const resourceTab=e.target.closest('[data-resource-tab]');if(resourceTab){setResourceTab(resourceTab.dataset.resourceTab);return}
    const resourceAction=e.target.closest('[data-resource-action]');if(resourceAction){showToast(resourceAction.dataset.resourceAction==='preview'?'已打开文件预览':'已开始模拟下载');return}
    if(e.target.closest('[data-preview-close]')){closePreviewDrawer();return}
    const mode=e.target.closest('[data-view-mode]');if(mode){if(mode.dataset.viewMode==='preview')openPreviewDrawer();return}
    if(e.target.closest('.ep-child'))return
    const jump=e.target.closest('[data-jump-step]');if(jump){selectStep(Number(jump.dataset.jumpStep));return}
    const card=e.target.closest('[data-step]');if(card){const stepIndex=Number(card.dataset.step);if(stepIndex===0&&state.mode==='default'&&!state.boundDevices.length){openDevicePicker();return}if(stepIndex===1&&state.mode==='default'&&!state.boundContacts.length){openContactPicker();return}if(stepIndex===2&&state.mode==='default'&&!state.selectedTemplate){openRegisterTemplates();return}if(stepIndex===12&&state.mode==='default'&&!state.steps[12].children[0].checked){generateReport('12.1');return}selectStep(stepIndex,{toggle:true});return}
    if(e.target.closest('.ep-flow')&&state.mode==='default'&&state.expanded!==null){state.expanded=null;renderFlow()}
  });
  document.addEventListener('change',e=>{const stepControl=e.target.closest('[data-step-input]');if(stepControl){updateStepControl(stepControl);return}const file=e.target.closest('[data-step-file]');if(file){const id=file.dataset.stepFile,[i]=id.split('.').map(Number),child=state.steps[i].children.find(x=>x.id===id);child.value=file.files[0]?.name||'';child.checked=!!child.value;state.steps[i].started=true;renderFlow();if(child.checked)completeStep(i);showToast(child.checked?'文件已上传':'未选择文件');return}const library=e.target.closest('[data-library-select]');if(library){libraryDraft=library.dataset.librarySelect;return}const spare=e.target.closest('[data-spare-name]');if(spare){if(spare.checked&&!spareDraft.includes(spare.dataset.spareName))spareDraft.push(spare.dataset.spareName);if(!spare.checked)spareDraft=spareDraft.filter(x=>x!==spare.dataset.spareName);return}const spareAll=e.target.closest('[data-spare-all]');if(spareAll){document.querySelectorAll('[data-spare-name]').forEach(x=>{x.checked=spareAll.checked;if(spareAll.checked&&!spareDraft.includes(x.dataset.spareName))spareDraft.push(x.dataset.spareName);if(!spareAll.checked)spareDraft=spareDraft.filter(name=>name!==x.dataset.spareName)});return}const register=e.target.closest('[data-register-select]');if(register){registerDraft=register.dataset.registerSelect;document.querySelectorAll('.ep-register-table tbody tr').forEach(x=>x.classList.toggle('selected',!!x.querySelector(`[data-register-select="${registerDraft}"]`)));return}const contactAll=e.target.closest('[data-contact-all]');if(contactAll){document.querySelectorAll('[data-contact-id]').forEach(x=>{x.checked=contactAll.checked;if(contactAll.checked&&!contactDraft.includes(x.dataset.contactId))contactDraft.push(x.dataset.contactId);if(!contactAll.checked)contactDraft=contactDraft.filter(id=>id!==x.dataset.contactId)});syncContactSelected();return}const contact=e.target.closest('[data-contact-id]');if(contact){if(contact.checked&&!contactDraft.includes(contact.dataset.contactId))contactDraft.push(contact.dataset.contactId);if(!contact.checked)contactDraft=contactDraft.filter(id=>id!==contact.dataset.contactId);syncContactSelected();return}const all=e.target.closest('[data-device-all]');if(all){document.querySelectorAll('[data-device-id]').forEach(x=>x.checked=all.checked);return}const device=e.target.closest('[data-resource-device]');if(device){resourceDeviceType=device.value;setResourceTab(resourceTabKey);return}const input=e.target.closest('[data-child]');if(input)toggleChild(input)});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&previewDrawer){closePreviewDrawer();return}if(e.key==='Escape'&&document.querySelector('.ep-report-shell')){closeReport();return}if(e.key==='Escape'&&document.querySelector('.ep-library-shell')){closeLibraryPicker();return}if(e.key==='Escape'&&document.querySelector('.ep-spare-shell')){closeSparePicker();return}if(e.key==='Escape'&&document.querySelector('.ep-register-shell')){closeRegisterTemplates();return}if(e.key==='Escape'&&document.querySelector('.ep-contact-shell')){closeContactPicker();return}if(e.key==='Escape'&&document.querySelector('.ep-device-shell')){closeDevicePicker();return}if(e.key==='Escape'&&resourceDrawer){closeResourceDrawer();return}const card=e.target.closest('[data-step]');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();card.click()}});
  window.addEventListener('hashchange',()=>{closePreviewDrawer(true);closeResourceDrawer(true);closeReport();closeLibraryPicker();closeSparePicker();closeDevicePicker();closeContactPicker();closeRegisterTemplates()});
})();
