(function(){
  const alarms=['接触网异物告警','轨道电路异常','道岔表示缺口','信号机灯丝告警'];
  const works=['成都端站','示例一站','示例三站','重庆端站'];
  const table=(type)=>`<table class="ps-table"><thead><tr>${(type==='alarm'?['序号','告警名称','告警类型','标题','状态']:['序号','当日派工单','当日销号单','作业人数']).map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${Array.from({length:4},(_,i)=>type==='alarm'?`<tr><td><i>${i+1}</i></td><td>${alarms[i]}</td><td>${['设备','环境','通信','电源'][i]}告警</td><td>待核查</td><td><span>处理中</span></td></tr>`:`<tr><td><i>${i+1}</i></td><td>${works[i]}维修</td><td>${i+1}项</td><td>${6+i*2}人</td></tr>`).join('')}</tbody></table>`;
  const donut=(title,total='6,832')=>`<section class="ps-panel ps-donut-panel"><h3>${title}</h3><div class="ps-donut-box"><div class="ps-donut"><div><b>${total}</b><small>合计</small></div></div><span class="l1">分类一: 450</span><span class="l2">分类二: 76</span><span class="l3">分类三: 87</span><span class="l4">分类四: 76</span><span class="l5">分类五: 23</span></div></section>`;
  const bars=(title,values=[142,171,198])=>`<section class="ps-panel ps-bar-panel"><h3>${title}</h3><div class="ps-bars" role="img" aria-label="${title}"><div class="ps-y"><span>200</span><span>150</span><span>100</span><span>50</span><span>0</span></div>${values.map((v,i)=>`<button class="ps-bar" style="--v:${v}" data-value="${v}" aria-label="${['优良 100','合格 86-100（不含）','不合格 86以下'][i]} ${v}"><i></i><span>${['优良 100','合格 86-100（不含）','不合格 86以下'][i]}</span></button>`).join('')}<output class="ps-chart-tip"></output></div></section>`;
  function panoramaScreen(){return `<div class="panorama-screen">
    <header class="ps-heading"><div class="ps-title"><strong>应急管理</strong><i></i></div><div class="ps-filters"><label><select id="psOrg"><option>某某组织机构</option><option>成都电务段</option><option>重庆电务段</option></select></label><label><select id="psPeriod"><option>近1个月</option><option>近3个月</option><option>近1年</option></select></label><button class="ps-query">查询</button><i class="ps-filter-divider" aria-hidden="true"></i><button class="ps-emergency-query"><span aria-hidden="true"></span>应急查询</button></div></header>
    <div class="ps-emergency-modal" hidden><section role="dialog" aria-modal="true" aria-labelledby="psEmergencyTitle"><header><b id="psEmergencyTitle">应急查询</b><button class="ps-emergency-modal-close" aria-label="关闭">×</button></header><div><label>应急类型<select id="psEmergencyType"><option value="">请选择</option><option value="fault">应急故障</option></select></label></div><footer><button class="ps-emergency-cancel">取消</button><button class="ps-emergency-confirm" disabled>进入详情</button></footer></section></div>
    <div class="ps-stage"><div class="ps-map" aria-label="成渝中线运维态势地图"></div>
      <div class="ps-column ps-left"><section class="ps-panel ps-table-panel"><h3>告警列表</h3>${table('alarm')}</section>${donut('设备数量')}${bars('设备状态-道岔标准')}</div>
      <div class="ps-column ps-right"><section class="ps-panel ps-table-panel"><h3>维修作业</h3>${table('work')}</section>${donut('问题状态')}${bars('设备状态-其他设备',[142,171,198])}</div>
      <div class="ps-stations" aria-label="地图车站">${[['成都端站',30,28],['示例一站',39,34],['示例二站',48,42],['示例三站',56,50],['示例四站',67,58],['示例五站',75,67],['示例六站',83,75],['重庆端站',88,84]].map(([name,x,y])=>`<button class="ps-station-hit" data-station="${name}" style="--x:${x}%;--y:${y}%" aria-label="查看${name}详情"></button>`).join('')}</div>
      <section class="ps-station-card" aria-live="polite" hidden><header><b>车站详情</b><button class="ps-station-close" aria-label="关闭">×</button></header><div class="ps-station-info"></div><button class="ps-emergency-start">启动应急</button></section>
    </div></div>`}
  window.PageViews.panoramaScreen=panoramaScreen;
  document.addEventListener('click',e=>{
    if(e.target.closest('.ps-query')){const org=document.querySelector('#psOrg')?.value,period=document.querySelector('#psPeriod')?.value;document.querySelector('#toast').textContent=`已查询 ${org} · ${period}`;document.querySelector('#toast').classList.add('show');setTimeout(()=>document.querySelector('#toast').classList.remove('show'),1700)}
    if(e.target.closest('.ps-emergency-query')){const modal=document.querySelector('.ps-emergency-modal');if(modal){modal.hidden=false;setTimeout(()=>modal.querySelector('select')?.focus(),0)}return}
    if(e.target.closest('.ps-emergency-modal-close,.ps-emergency-cancel')||e.target.classList.contains('ps-emergency-modal')){const modal=document.querySelector('.ps-emergency-modal');if(modal)modal.hidden=true;return}
    if(e.target.closest('.ps-emergency-confirm')){sessionStorage.setItem('emergency-station','示例三站');location.hash='#/panorama/emergency/process';return}
    const station=e.target.closest('.ps-station-hit');if(station){const card=document.querySelector('.ps-station-card'),name=station.dataset.station;card.querySelector('.ps-station-info').innerHTML=`<p>站名：<strong>${name}</strong></p><p>所属线路：<strong>成渝中线</strong></p><p>所属车间：<strong>${name.includes('成都')?'成都':'重庆'}信号车间</strong></p><p>所属工区：<strong>${name.replace('站','')}工区</strong></p><p>工区负责人：<strong>张明</strong></p><p>联系电话：<strong>138****2365</strong></p>`;card.hidden=false;card.style.left=`clamp(270px, ${Math.min(72,Math.max(20,Number(station.style.getPropertyValue('--x').replace('%',''))-8))}%, calc(100% - 330px))`;card.style.top=`clamp(60px, ${Math.min(58,Math.max(8,Number(station.style.getPropertyValue('--y').replace('%',''))-12))}%, calc(100% - 370px))`}
    if(e.target.closest('.ps-station-close'))e.target.closest('.ps-station-card').hidden=true;
    if(e.target.closest('.ps-emergency-start')){const name=e.target.closest('.ps-station-card').querySelector('.ps-station-info strong')?.textContent||'示例三站';sessionStorage.setItem('emergency-station',name);location.hash='#/panorama/emergency/process'}
  });
  document.addEventListener('change',e=>{if(e.target.id==='psEmergencyType'){const button=e.target.closest('.ps-emergency-modal').querySelector('.ps-emergency-confirm');button.disabled=e.target.value!=='fault'}});
  document.addEventListener('pointerover',e=>{const bar=e.target.closest('.ps-bar');if(!bar)return;const tip=bar.parentElement.querySelector('.ps-chart-tip');tip.textContent=`数量：${bar.dataset.value}`;tip.classList.add('show');tip.style.left=`${bar.offsetLeft+bar.offsetWidth/2}px`});
  document.addEventListener('pointerout',e=>{const bar=e.target.closest('.ps-bar');if(bar&&!bar.contains(e.relatedTarget))bar.parentElement.querySelector('.ps-chart-tip')?.classList.remove('show')});
})();
