(function(){
  const cfg=window.AppConfig;
  const home=document.querySelector('#homePage');
  const dynamic=document.querySelector('#dynamicPage');
  let openTabs=JSON.parse(sessionStorage.getItem('electric-tabs')||'null')||['#/workbench','#/person/home'];
  let historyTabs=JSON.parse(sessionStorage.getItem('electric-history')||'[]');

  function currentRoute(){return cfg.routes[location.hash]?location.hash:'#/person/home'}
  function persist(){sessionStorage.setItem('electric-tabs',JSON.stringify(openTabs));sessionStorage.setItem('electric-history',JSON.stringify(historyTabs));localStorage.setItem('electric-sidebar-collapsed',document.body.classList.contains('sidebar-collapsed')?'1':'0')}
  function navigate(route){if(location.hash===route){render()}else location.hash=route}
  function addTab(route){if(!openTabs.includes(route))openTabs.push(route);historyTabs=historyTabs.filter(x=>x!==route);historyTabs.push(route);persist()}
  function renderTabs(route){const box=document.querySelector('#quickTabs');box.innerHTML=openTabs.map(r=>{const item=cfg.routes[r];if(!item)return'';const fixed=r==='#/workbench';return `<button class="quick-tab ${r===route?'selected':''}" data-route="${r}">${item.title}${fixed?'':` <span class="tab-close" aria-label="关闭${item.title}">×</span>`}</button>`}).join('');requestAnimationFrame(()=>box.querySelector('.quick-tab.selected')?.scrollIntoView({block:'nearest',inline:'nearest'}))}
  function renderMenu(route){const item=cfg.routes[route],menu=cfg.menus[item.module]||[];document.querySelector('#sideNav').innerHTML=menu.map(x=>`<button data-route="${x.route}" class="${x.route===route?'active':''}"><span><img src="${x.icon}" alt=""></span>${x.title}</button>`).join('')}
  function render(){closeDrawer();closeStatsPersonModal();const route=currentRoute(),item=cfg.routes[route];addTab(route);document.querySelectorAll('.primary-nav button').forEach(b=>b.classList.toggle('active',b.dataset.module===item.module));renderMenu(route);renderTabs(route);if(item.view==='home'){home.hidden=false;dynamic.hidden=true}else{home.hidden=true;dynamic.hidden=false;dynamic.innerHTML=(window.PageViews[item.view]||window.PageViews.placeholder)(route)}document.title=`${item.title} · 成渝中线电务智能运维系统（I-PHM）`;persist()}
  function closeTab(route){if(route==='#/workbench')return;openTabs=openTabs.filter(x=>x!==route);historyTabs=historyTabs.filter(x=>x!==route);if(currentRoute()===route){const fallback=[...historyTabs].reverse().find(x=>openTabs.includes(x))||openTabs[openTabs.length-1]||'#/workbench';navigate(fallback)}else{renderTabs(currentRoute());persist()}}

  document.querySelector('.primary-nav').addEventListener('click',e=>{const b=e.target.closest('button[data-module]');if(b)navigate(cfg.moduleDefaults[b.dataset.module])});
  document.querySelector('#sideNav').addEventListener('click',e=>{const b=e.target.closest('button[data-route]');if(b)navigate(b.dataset.route)});
  document.querySelector('#quickTabs').addEventListener('click',e=>{const tab=e.target.closest('.quick-tab');if(!tab)return;if(e.target.closest('.tab-close'))closeTab(tab.dataset.route);else navigate(tab.dataset.route)});
  document.querySelector('#menuToggle').addEventListener('click',()=>{const c=document.body.classList.toggle('sidebar-collapsed');document.querySelector('#menuToggle').setAttribute('aria-expanded',String(!c));persist()});
  dynamic.addEventListener('click',e=>{
    if(e.target.closest('.order-detail'))navigate('#/work/orders/detail');
    if(e.target.closest('.back-link'))navigate('#/work/orders');
    const treeItem=e.target.closest('.org-tree li');if(treeItem){document.querySelectorAll('.org-tree li').forEach(x=>x.classList.remove('selected'));treeItem.classList.add('selected')}
    const sub=e.target.closest('.subtabs button');if(sub){sub.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));sub.classList.add('active')}
    const executionCard=e.target.closest('.execution aside button');if(executionCard)switchExecutionOrder(executionCard);
    const person=e.target.closest('.person-detail');if(person)openPersonDetail(Number(person.dataset.personId));
    const chartBar=e.target.closest('.clickable-bar');if(chartBar)openStatsPersonModal(chartBar);
    if(e.target.id==='personQuery')filterPeople();
    if(e.target.id==='personReset'){document.querySelector('#personSearch').value='';filterPeople()}
    if(e.target.id==='issueQuery')filterIssues();
    if(e.target.id==='issueReset')resetIssues();
    const issueCard=e.target.closest('.issue-summary');if(issueCard)selectIssueCard(issueCard);
    const issuePage=e.target.closest('.issue-pager button[data-page]');if(issuePage)changeIssuePage(issuePage);
    if(e.target.closest('.ledger-query'))toast('已按当前条件查询备品台账');
    if(e.target.closest('.ledger-reset')){document.querySelectorAll('.ledger-page select').forEach(x=>x.selectedIndex=0);toast('筛选条件已重置')}
    if(e.target.closest('.emergency-query'))toast('已按当前条件查询应急预案');
    if(e.target.closest('.emergency-reset')){document.querySelectorAll('.emergency-page>.filter-bar select').forEach(x=>x.selectedIndex=0);toast('筛选条件已重置')}
    if(e.target.closest('.emergency-add'))openEmergencyModal('新增');
    if(e.target.closest('.emergency-edit'))openEmergencyModal('修改');
    if(e.target.closest('.emergency-close,.emergency-cancel')||e.target.classList.contains('emergency-modal-mask'))closeEmergencyModal();
    if(e.target.closest('.emergency-delete')){e.target.closest('tr')?.remove();toast('已删除该预案')}
  });
  document.querySelector('#drawerBody').addEventListener('click',e=>{const tabButton=e.target.closest('.person-drawer-tab');if(!tabButton)return;const view=tabButton.closest('.person-detail-view'),person=window.PersonData.records.find(x=>x.id===Number(view.dataset.personId));if(!person)return;view.querySelectorAll('.person-drawer-tab').forEach(x=>x.classList.remove('active'));tabButton.classList.add('active');view.querySelector('.person-detail-table-wrap').innerHTML=window.PersonData.renderDetailTable(tabButton.dataset.detailTab,person)});
  function openPersonDetail(id){const person=window.PersonData.records.find(x=>x.id===id);if(!person)return;const drawer=document.querySelector('#drawer'),body=document.querySelector('#drawerBody');document.querySelector('#drawerTitle').textContent='详情';body.innerHTML=window.PersonData.renderDetail(person);drawer.classList.add('person-detail-drawer','open');document.querySelector('#drawerMask').classList.add('open');document.body.classList.add('drawer-open');body.scrollTop=0}
  function statsPersonRows(bar){const source=window.PersonData.records,series=bar.dataset.series;let rows=series==='男'?source.filter(x=>x.gender==='男'):series==='女'?source.filter(x=>x.gender==='女'):source;return rows.map((p,i)=>`<tr><td>${i+1}</td><td>${p.name}</td><td>****${['1234','5678','9012','3456','7890','2345','6789','0123','4567','8901'][p.id-1]}</td><td>***</td><td>IT工程师</td><td>${p.title}</td><td>${p.politics}</td><td>${p.gender}</td><td>${i<3?'<span class="tag blue">联锁试验</span> <span class="tag orange">营业线施工</span>':''}</td><td>${p.score}分</td></tr>`).join('')}
  function openStatsPersonModal(bar){const modal=document.querySelector('#statsPersonModal');document.querySelector('#statsPersonContext').textContent=`${bar.dataset.chartType} / ${bar.dataset.group}${bar.dataset.series==='人员'?'':` / ${bar.dataset.series}`}`;document.querySelector('#statsPersonRows').innerHTML=statsPersonRows(bar);modal.classList.add('show');document.body.classList.add('stats-modal-open')}
  function closeStatsPersonModal(){document.querySelector('#statsPersonModal')?.classList.remove('show');document.body.classList.remove('stats-modal-open')}
  document.querySelector('#statsPersonModal').addEventListener('click',e=>{if(e.target===e.currentTarget||e.target.closest('.stats-person-close'))closeStatsPersonModal()});
  dynamic.addEventListener('keydown',e=>{const bar=e.target.closest('.clickable-bar');if(bar&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openStatsPersonModal(bar)}});
  function openEmergencyModal(title){const mask=document.querySelector('.emergency-modal-mask');if(!mask)return;mask.querySelector('#emergencyModalTitle').textContent=title;mask.classList.add('show')}
  function closeEmergencyModal(){document.querySelector('.emergency-modal-mask')?.classList.remove('show')}
  dynamic.addEventListener('input',e=>{if(e.target.matches('.emergency-modal textarea')){const counter=e.target.closest('label').querySelector('small i');if(counter)counter.textContent=e.target.value.length}});
  dynamic.addEventListener('change',e=>{if(e.target.id==='planFile'){const box=e.target.closest('.upload-box'),name=e.target.files?.[0]?.name;if(name){box.querySelector('b').textContent=name;box.classList.add('has-file')}}});
  dynamic.addEventListener('submit',e=>{if(e.target.id!=='emergencyForm')return;e.preventDefault();const tbody=document.querySelector('#emergencyRows');const count=tbody?.querySelectorAll('tr').length||0;if(tbody&&document.querySelector('#emergencyModalTitle').textContent==='新增')tbody.insertAdjacentHTML('afterbegin',`<tr><td>${count+1}</td><td>某机构1</td><td>某车站一</td><td>新建应急预案</td><td>新建预案介绍</td><td>11</td><td>某某某</td><td>某线1</td><td>2026年09月21日12时00分00秒</td><td><button class="text-btn emergency-edit">修改</button>　<button class="danger-btn emergency-delete">删除</button></td></tr>`);closeEmergencyModal();toast('预案已保存')});
  function filterPeople(){const q=(document.querySelector('#personSearch')?.value||'').trim();document.querySelectorAll('#personRows tr').forEach(tr=>tr.hidden=q&&!tr.textContent.includes(q))}
  function filterIssues(){const map={status:'#issueStatus',department:'#issueDepartment',workshop:'#issueWorkshop',station:'#issueStation'},filters=Object.fromEntries(Object.entries(map).map(([key,id])=>[key,document.querySelector(id)?.value||''])),rows=window.IssueData.rows.filter(row=>Object.entries(filters).every(([key,value])=>!value||row[key]===value));document.querySelector('#issueRows').innerHTML=window.IssueData.renderRows(rows);const delta=Math.max(0,window.IssueData.rows.length-rows.length);document.querySelectorAll('.issue-summary strong').forEach((el,i)=>{el.innerHTML=`${Math.max(0,23.23-delta*(.37+i*.09)).toFixed(2)}<small>%</small>`});toast(`已查询到 ${rows.length} 条问题记录`)}
  function resetIssues(){document.querySelectorAll('.issue-filter select').forEach(x=>x.selectedIndex=0);document.querySelector('#issueRows').innerHTML=window.IssueData.renderRows(window.IssueData.rows);document.querySelectorAll('.issue-summary strong').forEach(el=>{el.innerHTML='23.23<small>%</small>'});document.querySelectorAll('.issue-summary').forEach(x=>x.classList.remove('active'));toast('问题管控筛选条件已重置')}
  function selectIssueCard(card){document.querySelectorAll('.issue-summary').forEach(x=>x.classList.toggle('active',x===card));const device=window.IssueData.devices.find(x=>x.key===card.dataset.device);if(device)toast(`${device.name}：录入率、处置率、超期率和告警率均为 23.23%`)}
  function changeIssuePage(button){button.closest('.issue-pager').querySelectorAll('button[data-page]').forEach(x=>x.classList.remove('active'));button.classList.add('active');const page=Number(button.dataset.page)||1;const rotated=[...window.IssueData.rows.slice(page%window.IssueData.rows.length),...window.IssueData.rows.slice(0,page%window.IssueData.rows.length)];document.querySelector('#issueRows').innerHTML=window.IssueData.renderRows(rotated);toast(`已切换到第 ${page} 页`)}
  dynamic.addEventListener('pointerover',e=>{const bar=e.target.closest('.issue-bar');if(!bar)return;const tip=bar.closest('.issue-chart').querySelector('.issue-chart-tooltip'),rect=bar.getBoundingClientRect();tip.innerHTML=`<b>${bar.dataset.device} · ${bar.dataset.station}</b><br>${bar.dataset.series}：${bar.dataset.value}`;tip.style.left=`${Math.min(window.innerWidth-150,rect.left+rect.width/2+10)}px`;tip.style.top=`${Math.max(8,rect.top-52)}px`;tip.classList.add('show')});
  dynamic.addEventListener('pointerout',e=>{const bar=e.target.closest('.issue-bar');if(bar&&!bar.contains(e.relatedTarget))bar.closest('.issue-chart').querySelector('.issue-chart-tooltip')?.classList.remove('show')});
  dynamic.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='personSearch')filterPeople()});
  function normalizeGenderIcons(){document.querySelectorAll('.gender-card strong').forEach(el=>{if(el.textContent.includes('👤'))el.innerHTML=`<span class="people-icons">${'<i></i>'.repeat(5)}</span>4678<small>人</small>`})}
  function normalizeTreeIcons(){document.querySelectorAll('.org-tree li').forEach(item=>{[...item.childNodes].filter(node=>node.nodeType===Node.TEXT_NODE&&node.textContent.trim()).forEach(node=>{const label=node.textContent.replace(/[▾▸▧　]/g,'').trim();if(!label)return;const row=document.createElement('span');row.className='tree-node-label';const icon=document.createElement('img');icon.src='assets/tree-node.png';icon.alt='';row.append(icon,document.createTextNode(label));node.replaceWith(row)})})}
  function normalizeOrderDetail(){const summary=document.querySelector('.order-summary');if(!summary)return;summary.querySelectorAll('.plan-copy p').forEach(p=>{if(p.textContent.trim().startsWith('2. 进行秋季设备鉴定'))p.remove()});const people=summary.querySelector('.submitters');if(people&&!people.dataset.iconized){people.dataset.iconized='1';people.innerHTML='<span><img src="assets/order-submitter.svg" alt="">提交人：肖鹏</span><span><img src="assets/order-approver.svg" alt="">审核人：王勇</span>'}}
  const executionOrders=[{staff:['室内操作人员：-','到位干部：王勇','质量验收员：王旭','作业人员：敖一帆、张奥攀、王旭'],rows:[['单项工作','电缆全程对地绝缘测试','(1)','(1)','敖一帆、张奥攀、王旭'],['检修工作','轨道胶接绝缘测试','(1)','23#','敖一帆、张奥攀、王旭'],['巡检工作','道岔加密清扫油润','道岔转换设备(13)','10#、12#、14#、16#','敖一帆、张奥攀、王旭']],tool:'短路铜线安设位置：垂停　　设撤负责人：-',other:['1. 严格执行三清点一确认制度，防松防脱一人检查一人录制制度。','2. 进出网全程录制视频并拍照上传车间盯控群。'],risk:'所有上道工器具必须认真执行三清点一确认，严禁未清点带入网内。',result:'任务完成及问题记录：无'},{staff:['室内操作人员：李斌','到位干部：赵强','质量验收员：陈杰','作业人员：周静、黄丽、徐磊'],rows:[['检修工作','信号机灯光及机构检查','(4)','X1、X3、S2、S4','周静、黄丽'],['测试工作','轨道电路电压测试','(6)','1G、3G、5G','陈杰、徐磊'],['整治工作','转辙机缺口调整与油润','道岔转换设备(8)','2#、4#、6#、8#','赵强、周静、徐磊']],tool:'短路铜线安设位置：龙兴站下行咽喉　　设撤负责人：赵强',other:['1. 作业前核对设备编号和作业范围，确认防护措施落实。','2. 完工后进行联锁关系复核并上传现场记录。'],risk:'测试过程中严格执行双人复核，严禁超范围作业。',result:'任务完成及问题记录：4#道岔表示杆已调整并复测正常。'}];
  function switchExecutionOrder(button){const box=button.closest('.execution'),buttons=[...box.querySelectorAll('aside button')],index=Math.max(0,buttons.indexOf(button)),data=executionOrders[index]||executionOrders[0];buttons.forEach(x=>x.classList.toggle('active',x===button));box.querySelector('article').innerHTML=`<h2>详情</h2><h3>一、人员安排</h3><div class="inline-details">${data.staff.map(x=>`<span>${x}</span>`).join('')}</div><h3>二、工作内容</h3><div class="table-wrap"><table class="design-table"><thead><tr><th>作业类型</th><th>工作类型及内容</th><th>计划数量</th><th>作业设备</th><th>作业人员</th></tr></thead><tbody>${data.rows.map(row=>`<tr>${row.map(cell=>`<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody></table></div><h3>三、工具</h3><p>${data.tool}</p><h3>四、其他安排</h3>${data.other.map(x=>`<p>${x}</p>`).join('')}<h3>五、主要安全风险</h3><p>${data.risk}</p><p>${data.result}</p>`}
  function normalizeVisuals(){normalizeGenderIcons();normalizeTreeIcons();normalizeOrderDetail()}
  new MutationObserver(normalizeVisuals).observe(dynamic,{childList:true,subtree:true});
  window.addEventListener('hashchange',render);
  if(localStorage.getItem('electric-sidebar-collapsed')==='1'){document.body.classList.add('sidebar-collapsed');document.querySelector('#menuToggle').setAttribute('aria-expanded','false')}
  document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;closeEmergencyModal();closeStatsPersonModal();if(document.querySelector('#drawer')?.classList.contains('open'))closeDrawer()});
  render();
  normalizeVisuals();
})();
