const metrics=[['本月作业次数',23,'次','metric-month-work.png'],['本月夜间天窗次数',23,'次','metric-night.png'],['作业负责人次数统计',23,'次','metric-owner.png'],['作业人员次数统计',23,'次','metric-worker.png'],['防护员次数统计',23,'次','metric-protector.png'],['工班长次数统计',23,'次','metric-foreman.png'],['年休假统计',23,'次','metric-leave.png']];
const rows=Array.from({length:23},(_,i)=>({id:i+1,no:'FHGD12472'+String(3657+i),unit:['信号中心','信号调度部','信号维护组','信号监控站','信号设备部','信号技术科','调度指挥中心'][i%7],area:'某某某车间',date:`2025-06-${String(18+(i%9)).padStart(2,'0')} 16:56:43`,content:i%3===0?'设备日常巡检':'作业内容作业内容作业内容',device:['信号机','轨道电路','道岔设备'][i%3],status:i%4===0?'待处理':'已完成'}));
let page=1,tab='orders';
const qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)];
function toast(msg){const e=qs('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function renderCalendar(){const el=qs('#calendarDays');const previous=['30','31'];const active=new Set([1,2,3,4,5,6,7,8,9,10,13,14,17,18]);el.innerHTML=[...previous.map(x=>`<button class="out">${x}</button>`),...Array.from({length:30},(_,i)=>{const d=i+1;return `<button data-day="${d}" class="${active.has(d)?'busy':''}">${String(d).padStart(2,'0')}</button>`}),...['01','02','03','04','05','06','07','08','09','10'].map(x=>`<button class="out">${x}</button>`)].join('');qsa('#calendarDays button[data-day]').forEach(b=>b.onclick=()=>{qsa('#calendarDays button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const tip=qs('#calendarTooltip');tip.querySelector('b').textContent=`${qs('#year').value}/${qs('#month').value.replace('月','').padStart(2,'0')}/${String(b.dataset.day).padStart(2,'0')}`;tip.classList.add('show')})}
function renderMetrics(){qs('#metricGrid').innerHTML=metrics.map((m,i)=>`<article class="metric" data-index="${i}"><div class="metric-icon"><img src="assets/${m[3]}" alt="" /></div><div><p>${m[0]}</p><strong>${m[1]}</strong><small>${m[2]}</small></div></article>`).join('');qsa('.metric').forEach(m=>m.onclick=()=>toast(`${metrics[m.dataset.index][0]}：${metrics[m.dataset.index][1]}次`))}
function filtered(){return rows}
function renderTable(){const data=filtered(),size=+qs('#pageSize').value,pages=Math.max(1,Math.ceil(data.length/size));page=Math.min(page,pages);const current=data.slice((page-1)*size,page*size);qs('#dataRows').innerHTML=current.map(r=>`<tr data-id="${r.id}"><td>${r.id}</td><td>${r.no}</td><td>${r.unit}</td><td>${r.area}</td><td>${r.date}</td><td>${r.content}</td><td>${r.device}</td></tr>`).join('')||'<tr><td colspan="7">暂无数据</td></tr>';qs('#totalRows').textContent=data.length;qs('#pageButtons').innerHTML=Array.from({length:Math.min(pages,6)},(_,i)=>`<button class="${page===i+1?'active':''}" data-page="${i+1}">${i+1}</button>`).join('');qs('#prevPage').disabled=page===1;qs('#nextPage').disabled=page===pages;qsa('#pageButtons button').forEach(b=>b.onclick=()=>{page=+b.dataset.page;renderTable()});qsa('#dataRows tr[data-id]').forEach(tr=>tr.onclick=()=>openDrawer(rows.find(r=>r.id==tr.dataset.id)))}
function openDrawer(r){qs('#drawerBody').innerHTML=`<div class="detail-list"><span>派工单号</span><b>${r.no}</b><span>单位</span><b>${r.unit}</b><span>车间/区间</span><b>${r.area}</b><span>作业日期</span><b>${r.date}</b><span>作业内容</span><b>${r.content}</b><span>作业设备</span><b>${r.device}</b></div>`;qs('#drawer').classList.add('open');qs('#drawerMask').classList.add('open')}
function closeDrawer(){qs('#drawer').classList.remove('open');qs('#drawerMask').classList.remove('open')}
qsa('#contentTabs button').forEach(b=>b.onclick=()=>{qsa('#contentTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');tab=b.dataset.tab;toast(`已切换至${b.textContent}`)});
qs('#pageSize').onchange=()=>{page=1;renderTable()};qs('#prevPage').onclick=()=>{if(page>1){page--;renderTable()}};qs('#nextPage').onclick=()=>{page++;renderTable()};qs('#closeDrawer').onclick=qs('#drawerMask').onclick=closeDrawer;
qsa('#year,#month').forEach(e=>e.onchange=()=>{qs('#calendarTooltip').classList.remove('show');toast(`已切换至 ${qs('#year').value}年${qs('#month').value}`)});document.addEventListener('click',e=>{if(!e.target.closest('.calendar-card'))qs('#calendarTooltip').classList.remove('show')});
renderCalendar();renderMetrics();renderTable();
